export const NATURES_FAILED = 'NATURES_FAILED';
export const NATURES_LOADING = 'NATURES_LOADING';
export const ADD_NATURES = 'ADD_NATURES';

export const COMMENTS_FAILED = 'COMMENTS_FAILED';
export const COMMENTS_LOADING = 'COMMENTS_LOADING';
export const ADD_COMMENTS = 'ADD_COMMENTS';
export const ADD_COMMENT = 'ADD_COMMENT';

export const TRAVELLERS_FAILED = 'TRAVELLERS_FAILED';
export const TRAVELLERS_LOADING = 'TRAVELLERS_LOADING';
export const ADD_TRAVELLERS = 'ADD_TRAVELLERS';

export const FAVORITES_LOADING = 'FAVORITES_LOADING';
export const FAVORITES_FAILED = 'FAVORITES_FAILED';
export const ADD_FAVORITES = 'ADD_FAVORITES';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';