export const NATURES_FAILED = 'NATURES_FAILED';
export const NATURES_LOADING = 'NATURES_LOADING';
export const ADD_NATURES = 'ADD_NATURES';


export const COMMENTS_FAILED = 'COMMENTS_FAILED';
export const COMMENTS_LOADING = 'COMMENTS_LOADING';
export const ADD_COMMENTS = 'ADD_COMMENTS';
export const ADD_COMMENT = 'ADD_COMMENT';

export const TRAVELLERS_FAILED = 'TRAVELLERS_FAILED';
export const TRAVELLERS_LOADING = 'TRAVELLERS_LOADING';
export const ADD_TRAVELLERS = 'ADD_TRAVELLERS';